In [1]:
import pandas as pd
import gdown
import os

import pandas as pd
import gdown
import os

## Downloading and checking data

In [2]:
msk_id = "1-tBXTuffgNsvuxkkF-rLyVByNtGyoOc3"
spb_id = "1ls4EFnoio3KG4oDS1IEkymoNAKER7eaB"
nn_id = "1uM5ZQ9MHtnl7Z7UB0eXmo2kXC5eSi3ns"
kaz_id = "1fyaHuzbb96T5cqbiYUcZRAtTOXT1Pbji"
ufa_id = "1B1DRO7HCfieKrp59Ea2PyDtaQvUIdXYZ"
novosib_id = "1MtmNW8F7JmZnWKNOHmJlvyIftgjdAlsk"
vlad_id = "1Q4nrePlch4YqJUlc9RTjD8UHKeMK4Gci"
msk_url = f"https://drive.google.com/uc?id={msk_id}"
spb_url = f"https://drive.google.com/uc?id={spb_id}"
nn_url = f"https://drive.google.com/uc?id={nn_id}"
kaz_url = f"https://drive.google.com/uc?id={kaz_id}"
ufa_url = f"https://drive.google.com/uc?id={ufa_id}"
novosib_url = f"https://drive.google.com/uc?id={novosib_id}"
vlad_url = f"https://drive.google.com/uc?id={vlad_id}"

url_by_city = {
  "msk": msk_url,
  "spb": spb_url,
  "nn": nn_url,
  "kaz": kaz_url,
  "ufa": ufa_url,
  "novosib": novosib_url,
  "vlad": vlad_url
}

for city, url in url_by_city.items():
    if not os.path.exists(f"{city}.csv"):
      gdown.download(url, f"{city}.csv")

In [3]:
msk_df = pd.read_csv("msk.csv", delimiter=";", on_bad_lines="skip")
spb_df = pd.read_csv("spb.csv", delimiter=";", on_bad_lines="skip")
nn_df = pd.read_csv("nn.csv", delimiter=";", on_bad_lines="skip")
kaz_df = pd.read_csv("kaz.csv", delimiter=";", on_bad_lines="skip")
ufa_df = pd.read_csv("ufa.csv", delimiter=";", on_bad_lines="skip")
novosib_df = pd.read_csv("novosib.csv", delimiter=";", on_bad_lines="skip")
vlad_df = pd.read_csv("vlad.csv", delimiter=";", on_bad_lines="skip")

In [4]:
msk_df = msk_df.loc[:, ~msk_df.columns.str.contains('^Unnamed')]

In [5]:
msk_df.head()

,Local time in Sheremetyevo (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
0,30.11.2023 23:30,-5.0,736.2,753.9,86.0,Wind blowing from the south-southwest,7,NaN,Light snow,Snow,Scattered clouds (40-50%) 420 m,4.7,-7.0
1,30.11.2023 23:00,-5.0,736.2,753.9,86.0,Wind blowing from the south-southwest,6,NaN,Light snow,NaN,Scattered clouds (40-50%) 630 m,8.0,-7.0
2,30.11.2023 22:30,-5.0,736.2,753.9,86.0,Wind blowing from the south-southwest,6,NaN,Light snow,NaN,Broken clouds (60-90%) 450 m,8.0,-7.0
3,30.11.2023 22:00,-5.0,735.4,753.1,86.0,Wind blowing from the south,7,NaN,Light snow,Snow,Broken clouds (60-90%) 330 m,5.0,-7.0
4,30.11.2023 21:30,-4.0,735.4,753.1,80.0,Wind blowing from the south,7,NaN,Light snow,NaN,Broken clouds (60-90%) 390 m,9.0,-7.0

In [6]:
msk_df.tail()

,Local time in Sheremetyevo (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
17463,01.12.2022 02:00,-13.0,762.6,781.6,85.0,Wind blowing from the east-northeast,3,NaN,NaN,NaN,No Significant Clouds,6.0,-15.0
17464,01.12.2022 01:30,-13.0,762.6,781.6,85.0,Wind blowing from the east-northeast,3,NaN,NaN,NaN,No Significant Clouds,6.0,-15.0
17465,01.12.2022 01:00,-13.0,762.6,781.6,92.0,Wind blowing from the east-northeast,3,NaN,NaN,NaN,No Significant Clouds,6.0,-14.0
17466,01.12.2022 00:30,-12.0,762.7,781.6,85.0,Wind blowing from the east-northeast,3,NaN,NaN,NaN,No Significant Clouds,6.0,-14.0
17467,01.12.2022 00:00,-13.0,762.6,781.6,92.0,Wind blowing from the east-northeast,3,NaN,NaN,NaN,No Significant Clouds,6.0,-14.0

In [7]:
spb_df = spb_df.loc[:, ~spb_df.columns.str.contains('^Unnamed')]

In [8]:
spb_df.head()

,Local time in Pulkovo (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
0,30.11.2023 23:30,-4.0,748.5,750.8,86.0,Wind blowing from the east-northeast,3,NaN,"Light shower(s), snow",NaN,"Scattered clouds (40-50%) 330 m, broken clouds...",9.0,-6.0
1,30.11.2023 23:00,-4.0,749.3,751.6,86.0,Wind blowing from the east-northeast,6,NaN,"Light shower(s), snow, low drifting, snow",NaN,"Scattered clouds (40-50%) 360 m, broken clouds...",7.0,-6.0
2,30.11.2023 22:30,-4.0,749.3,751.6,86.0,Wind blowing from the east,3,NaN,"Light shower(s), snow, low drifting, snow",NaN,"Scattered clouds (40-50%) 360 m, broken clouds...",7.0,-6.0
3,30.11.2023 22:00,-4.0,749.3,751.6,86.0,Wind blowing from the east-northeast,6,NaN,"Light shower(s), snow, low drifting, snow",NaN,"Scattered clouds (40-50%) 360 m, broken clouds...",9.0,-6.0
4,30.11.2023 21:30,-4.0,749.3,751.6,86.0,Wind blowing from the east-northeast,6,NaN,"Light shower(s), snow, low drifting, snow",NaN,"Scattered clouds (40-50%) 330 m, broken clouds...",10.0 and more,-6.0

In [9]:
spb_df.tail()

,Local time in Pulkovo (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
17487,01.12.2022 02:00,-4.0,776.9,779.3,74.0,Wind blowing from the south-east,2,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-8.0
17488,01.12.2022 01:30,-4.0,776.9,779.3,74.0,Wind blowing from the south-east,2,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-8.0
17489,01.12.2022 01:00,-4.0,776.9,779.3,74.0,variable wind direction,1,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-8.0
17490,01.12.2022 00:30,-4.0,776.9,779.3,74.0,Wind blowing from the south-east,2,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-8.0
17491,01.12.2022 00:00,-4.0,776.9,779.3,74.0,variable wind direction,1,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-8.0

In [10]:
nn_df = nn_df.loc[:, ~nn_df.columns.str.contains('^Unnamed')]

In [11]:
nn_df.head()

,Local time in Nizhny Novgorod (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
0,30.11.2023 23:30,-1.0,750.8,758.2,75.0,Wind blowing from the south-southwest,5.0,NaN,NaN,NaN,Overcast (100%) 1170 m,10.0 and more,-5.0
1,30.11.2023 23:00,0.0,750.8,758.2,80.0,Wind blowing from the south,5.0,NaN,Light snow,NaN,Overcast (100%) 720 m,10.0 and more,-3.0
2,30.11.2023 22:30,0.0,750.8,758.2,87.0,Wind blowing from the south,3.0,NaN,NaN,NaN,Overcast (100%) 870 m,10.0 and more,-2.0
3,30.11.2023 22:00,0.0,750.8,758.2,87.0,Wind blowing from the south,3.0,NaN,NaN,NaN,Overcast (100%) 1200 m,10.0 and more,-2.0
4,30.11.2023 21:30,0.0,750.8,758.2,93.0,Wind blowing from the south,3.0,NaN,NaN,NaN,Overcast (100%) 480 m,10.0 and more,-1.0

In [12]:
nn_df.tail()

,Local time in Nizhny Novgorod (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
17469,01.12.2022 02:00,-17.0,775.7,783.8,85.0,"Calm, no wind",0.0,NaN,Mist,NaN,No Significant Clouds,5.0,-19.0
17470,01.12.2022 01:30,-17.0,775.7,783.8,85.0,"Calm, no wind",0.0,NaN,Mist,NaN,No Significant Clouds,5.0,-19.0
17471,01.12.2022 01:00,-17.0,775.7,783.8,85.0,"Calm, no wind",0.0,NaN,Mist,NaN,No Significant Clouds,5.0,-19.0
17472,01.12.2022 00:30,-17.0,775.7,783.8,85.0,"Calm, no wind",0.0,NaN,Mist,NaN,Few clouds (10-30%) 120 m,4.2,-19.0
17473,01.12.2022 00:00,-17.0,775.7,783.8,85.0,"Calm, no wind",0.0,NaN,Mist,NaN,No Significant Clouds,4.9,-19.0

In [13]:
kaz_df = kaz_df.loc[:, ~kaz_df.columns.str.contains('^Unnamed')]

In [14]:
kaz_df.head()

,Local time in Kazan (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
0,30.11.2023 23:30,-3.0,750.3,761.2,93.0,Wind blowing from the east-southeast,7,NaN,Freezing (supercooled) rain,NaN,Overcast (100%) 480 m,2.0,-4.0
1,30.11.2023 23:00,-3.0,750.3,761.2,93.0,Wind blowing from the south-east,7,NaN,Light freezing (supercooled) rain,NaN,Overcast (100%) 870 m,8.0,-4.0
2,30.11.2023 22:30,-3.0,750.3,761.2,93.0,Wind blowing from the east-southeast,8,NaN,"Light snow,blowing snow",NaN,Overcast (100%) 810 m,5.0,-4.0
3,30.11.2023 22:00,-3.0,751.1,762.0,86.0,Wind blowing from the east-southeast,6,NaN,"Light snow, low drifting, snow",NaN,Overcast (100%) 270 m,9.0,-5.0
4,30.11.2023 21:30,-3.0,751.1,762.0,86.0,Wind blowing from the east-southeast,7,NaN,"Light snow, low drifting, snow",NaN,Overcast (100%) 960 m,10.0 and more,-5.0

In [15]:
kaz_df.tail()

,Local time in Kazan (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
17462,01.12.2022 02:00,-12.0,770.7,782.3,85.0,Wind blowing from the west,2,NaN,Mist,NaN,Overcast (100%) 120 m,2.3,-14.0
17463,01.12.2022 01:30,-11.0,770.8,782.3,79.0,Wind blowing from the west,2,NaN,Mist,NaN,Overcast (100%) 150 m,4.6,-14.0
17464,01.12.2022 01:00,-11.0,770.8,782.3,85.0,Wind blowing from the west,2,NaN,NaN,NaN,Overcast (100%) 120 m,8.0,-13.0
17465,01.12.2022 00:30,-11.0,770.8,782.3,85.0,Wind blowing from the west,2,NaN,Mist,NaN,Overcast (100%) 120 m,5.0,-13.0
17466,01.12.2022 00:00,-11.0,770.8,782.3,85.0,Wind blowing from the west,2,NaN,NaN,NaN,Overcast (100%) 90 m,8.0,-13.0

In [16]:
ufa_df = ufa_df.loc[:, ~ufa_df.columns.str.contains('^Unnamed')]

In [17]:
ufa_df.head()

,Local time in Ufa (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
0,30.11.2023 23:30,-11.0,753.7,767.3,85.0,Wind blowing from the south-west,4,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-13.0
1,30.11.2023 23:00,-12.0,753.7,767.3,85.0,Wind blowing from the south-southwest,3,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-14.0
2,30.11.2023 22:30,-12.0,753.7,767.3,85.0,Wind blowing from the south-west,4,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-14.0
3,30.11.2023 22:00,-11.0,753.7,767.3,85.0,Wind blowing from the south-west,3,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-13.0
4,30.11.2023 21:30,-11.0,753.7,767.3,79.0,Wind blowing from the south-southwest,1,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-14.0

In [18]:
ufa_df.tail()

,Local time in Ufa (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
17459,01.12.2022 02:00,-17.0,766.7,780.8,85.0,Wind blowing from the north-west,2,NaN,NaN,NaN,Broken clouds (60-90%) 600 m,10.0 and more,-19.0
17460,01.12.2022 01:30,-17.0,766.7,780.8,85.0,Wind blowing from the west-northwest,2,NaN,NaN,NaN,Broken clouds (60-90%) 600 m,10.0 and more,-19.0
17461,01.12.2022 01:00,-17.0,765.9,780.0,92.0,Wind blowing from the north-west,2,NaN,NaN,NaN,Broken clouds (60-90%) 600 m,10.0 and more,-18.0
17462,01.12.2022 00:30,-16.0,765.9,780.0,85.0,Wind blowing from the north-west,2,NaN,NaN,NaN,Broken clouds (60-90%) 600 m,10.0 and more,-18.0
17463,01.12.2022 00:00,-16.0,765.9,780.0,85.0,Wind blowing from the north-west,2,NaN,NaN,NaN,Broken clouds (60-90%) 420 m,10.0 and more,-18.0

In [19]:
novosib_df = novosib_df.loc[:, ~novosib_df.columns.str.contains('^Unnamed')]

In [20]:
novosib_df.head()

,Local time in Tolmachevo (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
0,30.11.2023 23:30,2.0,756.7,766.6,93,Wind blowing from the south-southwest,4,NaN,NaN,NaN,Overcast (100%) 330 m,10.0 and more,1.0
1,30.11.2023 23:00,2.0,756.7,766.6,87,Wind blowing from the south-southwest,4,NaN,NaN,NaN,Overcast (100%) 270 m,10.0 and more,0.0
2,30.11.2023 22:30,2.0,755.9,765.8,87,Wind blowing from the south-southwest,4,NaN,NaN,NaN,Overcast (100%) 330 m,10.0 and more,0.0
3,30.11.2023 22:00,2.0,755.9,765.8,87,Wind blowing from the south,4,NaN,NaN,NaN,Overcast (100%) 420 m,10.0 and more,0.0
4,30.11.2023 21:30,2.0,755.9,765.8,81,Wind blowing from the south,4,NaN,Light rain,NaN,No Significant Clouds,10.0 and more,-1.0

In [21]:
novosib_df.tail()

,Local time in Tolmachevo (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
17465,01.12.2022 02:00,-24.0,771.9,783.1,76,Wind blowing from the west-northwest,1,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-27.0
17466,01.12.2022 01:30,-25.0,771.9,783.1,83,Wind blowing from the north-west,1,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-27.0
17467,01.12.2022 01:00,-25.0,771.9,783.1,76,"Calm, no wind",0,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-28.0
17468,01.12.2022 00:30,-26.0,771.8,783.1,83,variable wind direction,1,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-28.0
17469,01.12.2022 00:00,-27.0,771.8,783.1,76,Wind blowing from the north-west,1,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-30.0

In [22]:
vlad_df = vlad_df.loc[:, ~vlad_df.columns.str.contains('^Unnamed')]

In [23]:
vlad_df.head()

,Local time in Vladivostok (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
0,30.11.2023 23:30,-16.0,765.9,767.3,72.0,"Calm, no wind",0,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-20.0
1,30.11.2023 23:00,-16.0,765.9,767.3,85.0,Wind blowing from the east-northeast,1,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-18.0
2,30.11.2023 22:30,-15.0,765.9,767.3,72.0,"Calm, no wind",0,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-19.0
3,30.11.2023 22:00,-15.0,765.9,767.3,72.0,Wind blowing from the north-northeast,1,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-19.0
4,30.11.2023 21:30,-15.0,765.9,767.3,78.0,"Calm, no wind",0,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-18.0

In [24]:
vlad_df.tail()

,Local time in Vladivostok (airport),T,P0,P,U,DD,Ff,ff10,WW,W'W',c,VV,Td
17459,01.12.2022 02:00,-20.0,768.1,769.6,71.0,Wind blowing from the north-northwest,1,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-24.0
17460,01.12.2022 01:30,-20.0,768.9,770.4,71.0,variable wind direction,1,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-24.0
17461,01.12.2022 01:00,-18.0,769.0,770.4,54.0,"Calm, no wind",0,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-25.0
17462,01.12.2022 00:30,-18.0,769.0,770.4,60.0,Wind blowing from the north,3,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-24.0
17463,01.12.2022 00:00,-15.0,769.0,770.4,46.0,Wind blowing from the south-west,4,NaN,NaN,NaN,No Significant Clouds,10.0 and more,-24.0

## Editing datasets

### Splitting by seasons

In [25]:
#splitting data by time of year
#Moscow
msk_df['Local time in Sheremetyevo (airport)'] = pd.to_datetime(msk_df['Local time in Sheremetyevo (airport)'], format='%d.%m.%Y %H:%M')
msk_df['month'] = msk_df['Local time in Sheremetyevo (airport)'].dt.month
msk_df_winter = msk_df[msk_df['month'].isin([12, 1, 2])].copy()
msk_df_spring = msk_df[msk_df['month'].isin([3, 4, 5])].copy()
msk_df_summer = msk_df[msk_df['month'].isin([6, 7, 8])].copy()
msk_df_autumn = msk_df[msk_df['month'].isin([9, 10, 11])].copy()

In [26]:
#splitting data by time of year
#Spb
spb_df['Local time in Pulkovo (airport)'] = pd.to_datetime(spb_df['Local time in Pulkovo (airport)'], format='%d.%m.%Y %H:%M')
spb_df['month'] = spb_df['Local time in Pulkovo (airport)'].dt.month
spb_df_winter = spb_df[spb_df['month'].isin([12, 1, 2])].copy()
spb_df_spring = spb_df[spb_df['month'].isin([3, 4, 5])].copy()
spb_df_summer = spb_df[spb_df['month'].isin([6, 7, 8])].copy()
spb_df_autumn = spb_df[spb_df['month'].isin([9, 10, 11])].copy()

In [27]:
#splitting data by time of year
#NN
nn_df['Local time in Nizhny Novgorod (airport)'] = pd.to_datetime(nn_df['Local time in Nizhny Novgorod (airport)'], format='%d.%m.%Y %H:%M')
nn_df['month'] = nn_df['Local time in Nizhny Novgorod (airport)'].dt.month
nn_df_winter = nn_df[nn_df['month'].isin([12, 1, 2])].copy()
nn_df_spring = nn_df[nn_df['month'].isin([3, 4, 5])].copy()
nn_df_summer = nn_df[nn_df['month'].isin([6, 7, 8])].copy()
nn_df_autumn = nn_df[nn_df['month'].isin([9, 10, 11])].copy()

In [28]:
#splitting data by time of year
#Kazan
kaz_df['Local time in Kazan (airport)'] = pd.to_datetime(kaz_df['Local time in Kazan (airport)'], format='%d.%m.%Y %H:%M')
kaz_df['month'] = kaz_df['Local time in Kazan (airport)'].dt.month
kaz_df_winter = kaz_df[kaz_df['month'].isin([12, 1, 2])].copy()
kaz_df_spring = kaz_df[kaz_df['month'].isin([3, 4, 5])].copy()
kaz_df_summer = kaz_df[kaz_df['month'].isin([6, 7, 8])].copy()
kaz_df_autumn = kaz_df[kaz_df['month'].isin([9, 10, 11])].copy()

In [29]:
#splitting data by time of year
#Ufa
ufa_df['Local time in Ufa (airport)'] = pd.to_datetime(ufa_df['Local time in Ufa (airport)'], format='%d.%m.%Y %H:%M')
ufa_df['month'] = ufa_df['Local time in Ufa (airport)'].dt.month
ufa_df_winter = ufa_df[ufa_df['month'].isin([12, 1, 2])].copy()
ufa_df_spring = ufa_df[ufa_df['month'].isin([3, 4, 5])].copy()
ufa_df_summer = ufa_df[ufa_df['month'].isin([6, 7, 8])].copy()
ufa_df_autumn = ufa_df[ufa_df['month'].isin([9, 10, 11])].copy()

In [30]:
#splitting data by time of year
#Novosibirsk
novosib_df['Local time in Tolmachevo (airport)'] = pd.to_datetime(novosib_df['Local time in Tolmachevo (airport)'], format='%d.%m.%Y %H:%M')
novosib_df['month'] = novosib_df['Local time in Tolmachevo (airport)'].dt.month
novosib_df_winter = novosib_df[novosib_df['month'].isin([12, 1, 2])].copy()
novosib_df_spring = novosib_df[novosib_df['month'].isin([3, 4, 5])].copy()
novosib_df_summer = novosib_df[novosib_df['month'].isin([6, 7, 8])].copy()
novosib_df_autumn = novosib_df[novosib_df['month'].isin([9, 10, 11])].copy()

In [31]:
#splitting data by time of year
#Vladivostok
vlad_df['Local time in Vladivostok (airport)'] = pd.to_datetime(vlad_df['Local time in Vladivostok (airport)'], format='%d.%m.%Y %H:%M')
vlad_df['month'] = vlad_df['Local time in Vladivostok (airport)'].dt.month
vlad_df_winter = vlad_df[vlad_df['month'].isin([12, 1, 2])].copy()
vlad_df_spring = vlad_df[vlad_df['month'].isin([3, 4, 5])].copy()
vlad_df_summer = vlad_df[vlad_df['month'].isin([6, 7, 8])].copy()
vlad_df_autumn = vlad_df[vlad_df['month'].isin([9, 10, 11])].copy()

### Splitting by bin

We will do binning by: month, day, three hours

In [32]:
def resample_seasonal_data(df, time_col):
    df = df.copy()
    df[time_col] = pd.to_datetime(df[time_col], format='%d.%m.%Y %H:%M', errors='coerce')
    df.set_index(time_col, inplace=True)

    numeric_cols = df.select_dtypes(include='number').columns
    categorical_cols = df.select_dtypes(include='object').columns

    def aggregate(group):
        return pd.concat([
            group[numeric_cols].mean(),
            group[categorical_cols].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
        ])

    df_weekly = df.resample('W').apply(aggregate)
    df_daily = df.resample('D').apply(aggregate)
    df_3h = df.resample('3H').apply(aggregate)

    return df_weekly, df_daily, df_3h

In [33]:
msk_df_winter_weekly, msk_df_winter_daily, msk_df_winter_3h = resample_seasonal_data(msk_df_winter, 'Local time in Sheremetyevo (airport)')
msk_df_spring_weekly, msk_df_spring_daily, msk_df_spring_3h = resample_seasonal_data(msk_df_spring, 'Local time in Sheremetyevo (airport)')
msk_df_summer_weekly, msk_df_summer_daily, msk_df_summer_3h = resample_seasonal_data(msk_df_summer, 'Local time in Sheremetyevo (airport)')
msk_df_autumn_weekly, msk_df_autumn_daily, msk_df_autumn_3h = resample_seasonal_data(msk_df_autumn, 'Local time in Sheremetyevo (airport)')

In [34]:
spb_df_winter_weekly, spb_df_winter_daily, spb_df_winter_3h = resample_seasonal_data(spb_df_winter, 'Local time in Pulkovo (airport)')
spb_df_spring_weekly, spb_df_spring_daily, spb_df_spring_3h = resample_seasonal_data(spb_df_spring, 'Local time in Pulkovo (airport)')
spb_df_summer_weekly, spb_df_summer_daily, spb_df_summer_3h = resample_seasonal_data(spb_df_summer, 'Local time in Pulkovo (airport)')
spb_df_autumn_weekly, spb_df_autumn_daily, spb_df_autumn_3h = resample_seasonal_data(spb_df_autumn, 'Local time in Pulkovo (airport)')

In [35]:
nn_df_winter_weekly, nn_df_winter_daily, nn_df_winter_3h = resample_seasonal_data(nn_df_winter, 'Local time in Nizhny Novgorod (airport)')
nn_df_spring_weekly, nn_df_spring_daily, nn_df_spring_3h = resample_seasonal_data(nn_df_spring, 'Local time in Nizhny Novgorod (airport)')
nn_df_summer_weekly, nn_df_summer_daily, nn_df_summer_3h = resample_seasonal_data(nn_df_summer, 'Local time in Nizhny Novgorod (airport)')
nn_df_autumn_weekly, nn_df_autumn_daily, nn_df_autumn_3h = resample_seasonal_data(nn_df_autumn, 'Local time in Nizhny Novgorod (airport)')

In [36]:
kaz_df_winter_weekly, kaz_df_winter_daily, kaz_df_winter_3h = resample_seasonal_data(kaz_df_winter, 'Local time in Kazan (airport)')
kaz_df_spring_weekly, kaz_df_spring_daily, kaz_df_spring_3h = resample_seasonal_data(kaz_df_spring, 'Local time in Kazan (airport)')
kaz_df_summer_weekly, kaz_df_summer_daily, kaz_df_summer_3h = resample_seasonal_data(kaz_df_summer, 'Local time in Kazan (airport)')
kaz_df_autumn_weekly, kaz_df_autumn_daily, kaz_df_autumn_3h = resample_seasonal_data(kaz_df_autumn, 'Local time in Kazan (airport)')

In [37]:
ufa_df_winter_weekly, ufa_df_winter_daily, ufa_df_winter_3h = resample_seasonal_data(ufa_df_winter, 'Local time in Ufa (airport)')
ufa_df_spring_weekly, ufa_df_spring_daily, ufa_df_spring_3h = resample_seasonal_data(ufa_df_spring, 'Local time in Ufa (airport)')
ufa_df_summer_weekly, ufa_df_summer_daily, ufa_df_summer_3h = resample_seasonal_data(ufa_df_summer, 'Local time in Ufa (airport)')
ufa_df_autumn_weekly, ufa_df_autumn_daily, ufa_df_autumn_3h = resample_seasonal_data(ufa_df_autumn, 'Local time in Ufa (airport)')

In [38]:
novosib_df_winter_weekly, novosib_df_winter_daily, novosib_df_winter_3h = resample_seasonal_data(novosib_df_winter, 'Local time in Tolmachevo (airport)')
novosib_df_spring_weekly, novosib_df_spring_daily, novosib_df_spring_3h = resample_seasonal_data(novosib_df_spring, 'Local time in Tolmachevo (airport)')
novosib_df_summer_weekly, novosib_df_summer_daily, novosib_df_summer_3h = resample_seasonal_data(novosib_df_summer, 'Local time in Tolmachevo (airport)')
novosib_df_autumn_weekly, novosib_df_autumn_daily, novosib_df_autumn_3h = resample_seasonal_data(novosib_df_autumn, 'Local time in Tolmachevo (airport)')

In [39]:
vlad_df_winter_weekly, vlad_df_winter_daily, vlad_df_winter_3h = resample_seasonal_data(vlad_df_winter, 'Local time in Vladivostok (airport)')
vlad_df_spring_weekly, vlad_df_spring_daily, vlad_df_spring_3h = resample_seasonal_data(vlad_df_spring, 'Local time in Vladivostok (airport)')
vlad_df_summer_weekly, vlad_df_summer_daily, vlad_df_summer_3h = resample_seasonal_data(vlad_df_summer, 'Local time in Vladivostok (airport)')
vlad_df_autumn_weekly, vlad_df_autumn_daily, vlad_df_autumn_3h = resample_seasonal_data(vlad_df_autumn, 'Local time in Vladivostok (airport)')

## Downloading obtained datasets

In [40]:
output_folder = "./result_datasets"
os.makedirs(output_folder, exist_ok=True)

In [41]:
dataset_names = ["msk_df_winter_weekly", "msk_df_winter_daily", "msk_df_winter_3h",
"msk_df_spring_weekly", "msk_df_spring_daily", "msk_df_spring_3h",
"msk_df_summer_weekly", "msk_df_summer_daily", "msk_df_summer_3h",
"msk_df_autumn_weekly", "msk_df_autumn_daily", "msk_df_autumn_3h",
"spb_df_winter_weekly", "spb_df_winter_daily", "spb_df_winter_3h",
"spb_df_spring_weekly", "spb_df_spring_daily", "spb_df_spring_3h",
"spb_df_summer_weekly", "spb_df_summer_daily", "spb_df_summer_3h",
"spb_df_autumn_weekly", "spb_df_autumn_daily", "spb_df_autumn_3h",
"nn_df_winter_weekly", "nn_df_winter_daily", "nn_df_winter_3h",
"nn_df_spring_weekly", "nn_df_spring_daily", "nn_df_spring_3h",
"nn_df_summer_weekly", "nn_df_summer_daily", "nn_df_summer_3h",
"nn_df_autumn_weekly", "nn_df_autumn_daily", "nn_df_autumn_3h",
"kaz_df_winter_weekly", "kaz_df_winter_daily", "kaz_df_winter_3h",
"kaz_df_spring_weekly", "kaz_df_spring_daily", "kaz_df_spring_3h",
"kaz_df_summer_weekly", "kaz_df_summer_daily", "kaz_df_summer_3h",
"kaz_df_autumn_weekly", "kaz_df_autumn_daily", "kaz_df_autumn_3h",
"ufa_df_winter_weekly", "ufa_df_winter_daily", "ufa_df_winter_3h",
"ufa_df_spring_weekly", "ufa_df_spring_daily", "ufa_df_spring_3h",
"ufa_df_summer_weekly", "ufa_df_summer_daily", "ufa_df_summer_3h",
"ufa_df_autumn_weekly", "ufa_df_autumn_daily", "ufa_df_autumn_3h",
"novosib_df_winter_weekly", "novosib_df_winter_daily", "novosib_df_winter_3h",
"novosib_df_spring_weekly", "novosib_df_spring_daily", "novosib_df_spring_3h",
"novosib_df_summer_weekly", "novosib_df_summer_daily", "novosib_df_summer_3h",
"novosib_df_autumn_weekly", "novosib_df_autumn_daily", "novosib_df_autumn_3h",
"vlad_df_winter_weekly", "vlad_df_winter_daily", "vlad_df_winter_3h",
"vlad_df_spring_weekly", "vlad_df_spring_daily", "vlad_df_spring_3h",
"vlad_df_summer_weekly", "vlad_df_summer_daily", "vlad_df_summer_3h",
"vlad_df_autumn_weekly", "vlad_df_autumn_daily", "vlad_df_autumn_3h"
]

In [42]:
flag = True

In [43]:
if flag:
  for name in dataset_names:
    df = globals().get(name)
    if df is not None:
        file_path = os.path.join(output_folder, f"{name}.csv")
        df.to_csv(file_path, index=False)
        print(f"Saved {name} to {file_path}")
    else:
        print(f"Dataset {name} not found!")

Saved msk_df_winter_weekly to ./result_datasets/msk_df_winter_weekly.csv
Saved msk_df_winter_daily to ./result_datasets/msk_df_winter_daily.csv
Saved msk_df_winter_3h to ./result_datasets/msk_df_winter_3h.csv
Saved msk_df_spring_weekly to ./result_datasets/msk_df_spring_weekly.csv
Saved msk_df_spring_daily to ./result_datasets/msk_df_spring_daily.csv
Saved msk_df_spring_3h to ./result_datasets/msk_df_spring_3h.csv
Saved msk_df_summer_weekly to ./result_datasets/msk_df_summer_weekly.csv
Saved msk_df_summer_daily to ./result_datasets/msk_df_summer_daily.csv
Saved msk_df_summer_3h to ./result_datasets/msk_df_summer_3h.csv
Saved msk_df_autumn_weekly to ./result_datasets/msk_df_autumn_weekly.csv
Saved msk_df_autumn_daily to ./result_datasets/msk_df_autumn_daily.csv
Saved msk_df_autumn_3h to ./result_datasets/msk_df_autumn_3h.csv
Saved spb_df_winter_weekly to ./result_datasets/spb_df_winter_weekly.csv
Saved spb_df_winter_daily to ./result_datasets/spb_df_winter_daily.csv
Saved spb_df_winter_3h to ./result_datasets/spb_df_winter_3h.csv
Saved spb_df_spring_weekly to ./result_datasets/spb_df_spring_weekly.csv
Saved spb_df_spring_daily to ./result_datasets/spb_df_spring_daily.csv
Saved spb_df_spring_3h to ./result_datasets/spb_df_spring_3h.csv
Saved spb_df_summer_weekly to ./result_datasets/spb_df_summer_weekly.csv
Saved spb_df_summer_daily to ./result_datasets/spb_df_summer_daily.csv
Saved spb_df_summer_3h to ./result_datasets/spb_df_summer_3h.csv
Saved spb_df_autumn_weekly to ./result_datasets/spb_df_autumn_weekly.csv
Saved spb_df_autumn_daily to ./result_datasets/spb_df_autumn_daily.csv
Saved spb_df_autumn_3h to ./result_datasets/spb_df_autumn_3h.csv
Saved nn_df_winter_weekly to ./result_datasets/nn_df_winter_weekly.csv
Saved nn_df_winter_daily to ./result_datasets/nn_df_winter_daily.csv
Saved nn_df_winter_3h to ./result_datasets/nn_df_winter_3h.csv
Saved nn_df_spring_weekly to ./result_datasets/nn_df_spring_weekly.csv
Saved nn_df_spring_daily to ./result_datasets/nn_df_spring_daily.csv
Saved nn_df_spring_3h to ./result_datasets/nn_df_spring_3h.csv
Saved nn_df_summer_weekly to ./result_datasets/nn_df_summer_weekly.csv
Saved nn_df_summer_daily to ./result_datasets/nn_df_summer_daily.csv
Saved nn_df_summer_3h to ./result_datasets/nn_df_summer_3h.csv
Saved nn_df_autumn_weekly to ./result_datasets/nn_df_autumn_weekly.csv
Saved nn_df_autumn_daily to ./result_datasets/nn_df_autumn_daily.csv
Saved nn_df_autumn_3h to ./result_datasets/nn_df_autumn_3h.csv
Saved kaz_df_winter_weekly to ./result_datasets/kaz_df_winter_weekly.csv
Saved kaz_df_winter_daily to ./result_datasets/kaz_df_winter_daily.csv
Saved kaz_df_winter_3h to ./result_datasets/kaz_df_winter_3h.csv
Saved kaz_df_spring_weekly to ./result_datasets/kaz_df_spring_weekly.csv
Saved kaz_df_spring_daily to ./result_datasets/kaz_df_spring_daily.csv
Saved kaz_df_spring_3h to ./result_datasets/kaz_df_spring_3h.csv
Saved kaz_df_summer_weekly to ./result_datasets/kaz_df_summer_weekly.csv
Saved kaz_df_summer_daily to ./result_datasets/kaz_df_summer_daily.csv
Saved kaz_df_summer_3h to ./result_datasets/kaz_df_summer_3h.csv
Saved kaz_df_autumn_weekly to ./result_datasets/kaz_df_autumn_weekly.csv
Saved kaz_df_autumn_daily to ./result_datasets/kaz_df_autumn_daily.csv
Saved kaz_df_autumn_3h to ./result_datasets/kaz_df_autumn_3h.csv
Saved ufa_df_winter_weekly to ./result_datasets/ufa_df_winter_weekly.csv
Saved ufa_df_winter_daily to ./result_datasets/ufa_df_winter_daily.csv
Saved ufa_df_winter_3h to ./result_datasets/ufa_df_winter_3h.csv
Saved ufa_df_spring_weekly to ./result_datasets/ufa_df_spring_weekly.csv
Saved ufa_df_spring_daily to ./result_datasets/ufa_df_spring_daily.csv
Saved ufa_df_spring_3h to ./result_datasets/ufa_df_spring_3h.csv
Saved ufa_df_summer_weekly to ./result_datasets/ufa_df_summer_weekly.csv
Saved ufa_df_summer_daily to ./result_datasets/ufa_df_summer_daily.csv
Saved ufa_df_summer_3h to ./result_datasets/ufa_df_summer_3h.csv
Saved ufa_df_autumn_weekly to ./result_datasets/ufa_df_autumn_weekly.csv
Saved ufa_df_autumn_daily to ./result_datasets/ufa_df_autumn_daily.csv
Saved ufa_df_autumn_3h to ./result_datasets/ufa_df_autumn_3h.csv
Saved novosib_df_winter_weekly to ./result_datasets/novosib_df_winter_weekly.csv
Saved novosib_df_winter_daily to ./result_datasets/novosib_df_winter_daily.csv
Saved novosib_df_winter_3h to ./result_datasets/novosib_df_winter_3h.csv
Saved novosib_df_spring_weekly to ./result_datasets/novosib_df_spring_weekly.csv
Saved novosib_df_spring_daily to ./result_datasets/novosib_df_spring_daily.csv
Saved novosib_df_spring_3h to ./result_datasets/novosib_df_spring_3h.csv
Saved novosib_df_summer_weekly to ./result_datasets/novosib_df_summer_weekly.csv
Saved novosib_df_summer_daily to ./result_datasets/novosib_df_summer_daily.csv
Saved novosib_df_summer_3h to ./result_datasets/novosib_df_summer_3h.csv
Saved novosib_df_autumn_weekly to ./result_datasets/novosib_df_autumn_weekly.csv
Saved novosib_df_autumn_daily to ./result_datasets/novosib_df_autumn_daily.csv
Saved novosib_df_autumn_3h to ./result_datasets/novosib_df_autumn_3h.csv
Saved vlad_df_winter_weekly to ./result_datasets/vlad_df_winter_weekly.csv
Saved vlad_df_winter_daily to ./result_datasets/vlad_df_winter_daily.csv
Saved vlad_df_winter_3h to ./result_datasets/vlad_df_winter_3h.csv
Saved vlad_df_spring_weekly to ./result_datasets/vlad_df_spring_weekly.csv
Saved vlad_df_spring_daily to ./result_datasets/vlad_df_spring_daily.csv
Saved vlad_df_spring_3h to ./result_datasets/vlad_df_spring_3h.csv
Saved vlad_df_summer_weekly to ./result_datasets/vlad_df_summer_weekly.csv
Saved vlad_df_summer_daily to ./result_datasets/vlad_df_summer_daily.csv
Saved vlad_df_summer_3h to ./result_datasets/vlad_df_summer_3h.csv
Saved vlad_df_autumn_weekly to ./result_datasets/vlad_df_autumn_weekly.csv
Saved vlad_df_autumn_daily to ./result_datasets/vlad_df_autumn_daily.csv
Saved vlad_df_autumn_3h to ./result_datasets/vlad_df_autumn_3h.csv